version: '3.1'

services:

  #db:
  #  image: mysql
  #  volumes:
  #    - ./mySQL/data/db:/var/lib/mysql
  #  # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #  # (this is just an example, not intended to be a production configuration)
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: rootPassword
  #    MYSQL_DATABASE: test
  #    MYSQL_USER: user
  #    MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  radius:
    image: frauhottelmann/daloradius-docker:1.2 #you need to change the tag to your arch and the desired version
    container_name: radius
    restart: always
    depends_on:
      - "radius-mysql" 
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
      - '80:80'
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=dalodbpass
      
  radius-mysql:
    image: mariadb:10.3 # use image: linuxserver/mariadb:arm32v7-110.3.18mariabionic-ls37 for RaspberryPi
    container_name: radius-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=dalodbpass
      - MYSQL_ROOT_PASSWORD=dalorootpass
    volumes:
      - ./radius-mysql:/var/lib/mysql